# Generated by Django 3.0.2 on 2021-02-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('topic', models.CharField(choices=[('POLITICS', 'Politics'), ('HEALTH', 'Health'), ('SPORT', 'Sport'), ('TECH', 'Tech')], max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_body', models.TextField()),
                ('expiration', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('EXPIRED', 'Expired')], max_length=7)),
                ('owner_fullname', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('comment', models.TextField(default='')),
                ('time_left', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piazza.Post')),
            ],
        ),
    ]
