# Generated by Django 3.0.2 on 2021-03-03 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import piazza.models


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piazza.Post', validators=[piazza.models.Interaction.validate_active]),
        ),
    ]
